// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const GlyphBSA: typeof import('~icons/glyph/b-s-a.jsx')['default']
  const GlyphManhattanHydraulics: typeof import('~icons/glyph/manhattan-hydraulics.jsx')['default']
  const GlyphOTD: typeof import('~icons/glyph/o-t-d.jsx')['default']
  const IconBSA: typeof import('~icons/icon/b-s-a.jsx')['default']
  const IconManhattanHydraulics: typeof import('~icons/icon/manhattan-hydraulics.jsx')['default']
  const MdiClose: typeof import('~icons/mdi/close.jsx')['default']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
export {}
